import type { NextPage } from "next";
import Head from "next/head";

import CustomHeader from "../containers/CustomHeader/CustomHeader";

import Container from "@mui/material/Container";

import HomePageItem from "../components/HomePageItem";
import Match from "../models/Match";

import { CircularProgress } from "@mui/material";
import { useEffect, useState } from "react";
import { useQuery } from "react-query";
import CenteredComponent from "../components/CenteredComponent";
//import { BetService } from "../services/BetService";
import { BookmakerService } from "../services/BookmakerService";
import { AuthService } from "../services/AuthService";
import { Column } from "../styles/shared-styles";
import Bookmakers from "../containers/Bookmakers";
import Divider from '@mui/material/Divider';
import FAB, { FloatingButtonFAB } from "../components/Dropdown/Fab";

import CasinoIcon from '@mui/icons-material/Casino';
import { useRouter } from "next/router";
import ItemProperty from "../components/ItemProperty";
import AvatarImage from "../components/AvatarImage";
import PromoImage from "../components/PromoImage";
import ShareButtons from "../components/ShareButtons";
import ServerError from "../models/ServerError";
import Alert from "../components/Alert/Alert";
import Voucher from "../models/Voucher";
import DetailsComponent from "../components/DetailsComponent";
import VoucherRules from "../components/VoucherProperties/VoucherRules";
import VoucherData from "../components/VoucherProperties/VoucherData";
import TakeVoucherButton from "../components/VoucherProperties/TakeVoucherButton";
import BookmakersData from "../components/BookmakersProperties/BookmakersData";
import CancelVoucherButton from "../components/VoucherProperties/CancelVoucherButton";
import Currency from "../models/Currency";
import { CurrencyService } from "../services/CurrencyService";
import CurrencyData from "../components/CurrencyProperties/CurrencyData";
import Bookmaker from "../models/Bookmaker";
import BookmakerFullData from "../components/BookmakersProperties/BookmakerFullData";

//const betService = new BetService();
const authService = new AuthService();
const bookmakerService = new BookmakerService();

const BookmakerCreated: NextPage = () => {


  const [successMessage, setSuccessMessage] = useState("");
  const [errorMessage, setErrorMessage] = useState("");
  const [bookmakerLocal, setBookmakerLocal] = useState<Bookmaker | undefined>(undefined);
  //const router = useRouter();
  const { push,query } = useRouter();
  const [logged, setLogged] = useState<Boolean>(false);

  const loading = !!!bookmakerLocal;
  const bookmakerLocalId = Number(query.bookmakerId)


  console.log(query.bookmakerId);
  console.log(bookmakerLocalId);
  //const { isLoading, error, data: user, isSuccess } = useQuery(['getUser'], authService.getUser);
  const { isLoading, error, data: bookmaker, isSuccess } = useQuery(['getBookmaker'], authService.getBookmaker);

  //const owner = match?.bookmaker?.id === bookmaker?.id;
  
  useEffect(() => {
    let active = true;
    console.log(loading);
    console.log(bookmakerLocal);
    console.log(bookmaker);
    console.log(bookmakerLocalId);
    console.log(query.bookmakerId);
    console.log(Number(query.bookmakerId));
    if (!loading) {
      return undefined;
    }

    if(!!bookmakerLocalId){
      bookmakerService.getBookmakerById(bookmakerLocalId).then((res)=>{
        console.log(res);
        setBookmakerLocal(res)
      }).catch((erro)=>{
        if(!!setErrorMessage){
          setErrorMessage(erro.message)
        }
      })
    }

    return () => {
        active = false;
    };
  });//, [loading,voucherId]);

  console.log(bookmakerLocal);

  useEffect(() => {
    setLogged(authService.isLogged);
  }, [bookmaker]);

  const newVoucher = () => {
    push('create-voucher');
  }

  const onEditHandler = (currency: Currency, changes: any, alertMessage: string) => {

      console.log(currency);
      console.log(changes);
      //const matchService = new MatchService();
      if(!!bookmakerLocal){
        bookmakerService.updateBookmaker(bookmakerLocal, changes)
          .then((_res: Bookmaker) => {
            setSuccessMessage(alertMessage)
            setBookmakerLocal(_res)
          })
          .catch((err: ServerError) => {
            console.log("Erro interno");
            setErrorMessage("Erro interno")
          });
      }
  };

  // if(!logged && !isLoading && (!!isSuccess || !!error)){
  //   push('login')
  // }

  return (
    <div>
      <Head>
        <title>{!!bookmakerLocal?`${"Site"}: ${bookmakerLocal?.hid}`:""}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CustomHeader />
      {isLoading || loading ? <CenteredComponent>
            <CircularProgress />
          </CenteredComponent> :
          <Container>
          <HomePageItem>
            {/* <MatchPromoImage/> com botões de edição e compartilhamento*/}
            <Column>
              <ItemProperty>
                <ShareButtons link={window.location.href} bannerLink={bookmakerLocal?.photo || bookmakerLocal?.logo}/>
              </ItemProperty>
            </Column>
          </HomePageItem>
          <HomePageItem>
            {/* <MatchPromoImage/> com botões de edição e compartilhamento*/}
           
            <Column>
              <ItemProperty>
                <PromoImage entity={bookmakerLocal} bookmaker={bookmaker || undefined} onEditHandler={onEditHandler}/>
              </ItemProperty>
            </Column>
          </HomePageItem>
          <HomePageItem>
            {/* <MatchImage/> com botões de edição e compartilhamento*/}
             
            <Column>
              <ItemProperty>
                <AvatarImage entity={bookmakerLocal} bookmaker={bookmaker || undefined} onEditHandler={onEditHandler}/>
              </ItemProperty>
            </Column>
          </HomePageItem>
          <HomePageItem>
            <ItemProperty>
              <VoucherRules voucher={bookmakerLocal} title={"Quem somos"}/> {/* descricao (nao editavel) */}
            </ItemProperty>
          </HomePageItem>
          <HomePageItem>
            <ItemProperty>
              <BookmakerFullData bookmakerLocal={bookmakerLocal} bookmaker={bookmaker || undefined} title={`Dados do ${"Site"}`} onEditHandler={onEditHandler}/> {/* informacoes editaveis do voucer (talvez seja visivel apenas para o owner) */}
            </ItemProperty>
          </HomePageItem>
          {/* <HomePageItem>
            <TakeVoucherButton voucher={voucher} bookmaker={bookmaker || undefined}/>
          </HomePageItem> */}
          {/* <HomePageItem>
            <BookmakersData bookmaker={bookmaker || undefined}/>
          </HomePageItem> */}
          {/* <HomePageItem>
            <CancelVoucherButton voucher={voucher} bookmaker={bookmaker || undefined}/>
          </HomePageItem> */}
          <Alert type="success" show={!!successMessage} closeAll={()=> setSuccessMessage("")}>
              <p>{successMessage}</p>
          </Alert>
          <Alert type="error" show={!!errorMessage} closeAll={()=> setErrorMessage("")}>
              <p>{errorMessage}</p>
          </Alert>
  
          <HomePageItem>
          <FloatingButtonFAB/>
          </HomePageItem>
          {/* <HomePageItem
            title="Bookmakers"
            showSeeMore
            seeMoreHandler={seeMoreHandler}
          >
          <Bookmakers bookmakers={bookmakers} size={listSize}></Bookmakers>
          </HomePageItem> */}
        </Container>
        }
      

      {/* <CreateBet/> */}
    </div>
  );
};

export default BookmakerCreated;
