import type { NextPage } from "next";
import Head from "next/head";

import CustomHeader from "../containers/CustomHeader/CustomHeader";

import Container from "@mui/material/Container";

import HomePageItem from "../components/HomePageItem";
import RequestedGenerics from "../containers/RequestedGenerics";
import SearchBets from "../containers/SearchBets";

import { CircularProgress } from "@mui/material";
import { useEffect, useState } from "react";
import { useQuery } from "react-query";
import CenteredComponent from "../components/CenteredComponent";
import { BetService } from "../services/BetService";
import { GenericService } from "../services/GenericService";
import { BookmakerService } from "../services/BookmakerService";
import { Column } from "../styles/shared-styles";
import Bookmakers from "../containers/Bookmakers";
import Divider from '@mui/material/Divider';
import FAB, { FloatingButtonFAB } from "../components/Dropdown/Fab";
import { useRouter } from "next/router";
import Event from "../models/Event";
import { EventService } from "../services/EventService";

import {styled} from "@mui/material";
import { ImagePromo } from "../components/ImagePromo";
import MostRequestedEventCard, { EventCard } from "../components/EventCard/EventCard";

const betService = new BetService();
const genericService = new GenericService();
const bookmakerService = new BookmakerService();
const eventService = new EventService();

export const TypeButton = styled("div")({
  color: "white",
  background: '#234A17',
  borderRadius: "15px",
  padding: ".5rem",
  margin: "5px"
})

export const BrandWrapper = styled("div")({
  display: "flex",
  alignItems: "center"
})

const EventCreated: NextPage = () => {

  //let queryStr:String | undefined = undefined;
  //let page:number = 0;
  //let size:number = 5;
  const [event, setEvent] = useState<Event | undefined>(undefined);
  const [queryStr, setQueryStr] = useState("");
  const [listSize, setListSize] = useState(5);
  const [page, setPage] = useState(0);
  //const {data: bookmakers } = useQuery(['getBookmakers'], bookmakerService.getBookmakers);
  const { push,query } = useRouter();
  const loading = !!!event;
  const eventId = Number(query.eventId);
  const { isLoading, error, data: mostRequested } = useQuery(['getGenericByEventPageAndSize',eventId,page,listSize,queryStr], 
  () => {return genericService.getGenericByEventPageAndSize(eventId,page,listSize,queryStr)});

  useEffect(() => {
    let active = true;
    console.log(loading);
    if (!loading) {
      return undefined;
    }
    const fetchMatch = async () => {
      setEvent(await eventService.getEventById(eventId));
        console.log(event);
    }

    fetchMatch().catch(()=>{
      console.log(eventId);
    });

    return () => {
        active = false;
    };
  }, [loading,eventId]);

  const seeMoreHandler = () => {
    setListSize(listSize + 5);
  };

  const search = (text:string) => {
    console.log(text.toUpperCase());
    if (text !== "") {
      setQueryStr(text.toUpperCase());
    }else{
      setQueryStr("");
    }
  };

  return (
    <div>
      <Head>
        <title>Matchingbet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CustomHeader children={<TypeButton>{"Evento"}</TypeButton>} style={{background: "#34B329"}}/>
      <Container>
        <HomePageItem>

          
          <BrandWrapper sx={{ flexGrow: 1 }}>
              <ImagePromo url={event?.photo} size = {150}/>
          </BrandWrapper>

        </HomePageItem>
        <HomePageItem>

          <EventCard event={event}/>

        </HomePageItem>
        <HomePageItem>


          <SearchBets 
          queryStr={queryStr}
          placeHolder={"Buscar vale cupons e apostas associadas a este evento"}
          search={search}
          />
        </HomePageItem>

        <HomePageItem
          //title="Matches"
          showSeeMore
          seeMoreHandler={seeMoreHandler}
        >
          {isLoading ? <CenteredComponent>
            <CircularProgress />
          </CenteredComponent> : 
          <Column>
            <RequestedGenerics requestedGenerics={mostRequested} size={listSize} page={page} queryStr={queryStr} />
            
          </Column>}
        </HomePageItem>
        <HomePageItem>
        <FloatingButtonFAB/>
        </HomePageItem>
        {/* <HomePageItem
          title="Bookmakers"
          showSeeMore
          seeMoreHandler={seeMoreHandler}
        >
        <Bookmakers bookmakers={bookmakers} size={listSize}></Bookmakers>
        </HomePageItem> */}
      </Container>

      {/* <CreateBet/> */}
    </div>
  );
};

export default EventCreated;
