export enum Endpoints {
  USERS = "users",
  BOOKMAKERS = "bookmakers",
  MATCHES = "matches",
  EVENTS = "events",
  EVENTS_FILTER = "events/filter",
  CATEGORIES_FILTER = "categories/filter",
  CURRENCIES = "currencies",
  CURRENCIES_BYVOUCHER = "currencies/voucher",
  CURRENCIES_FILTER = "currencies/filter",
  CURRENCIES_ME_FILTER = "currencies/me",
  VOUCHERS = "vouchers",
  VOUCHERS_TAKE = "vouchers/take",
  VOUCHERS_TAKEN = "vouchers/taken",
  VOUCHERS_CANCEL = "vouchers/cancel",
  VOUCHERS_FILTER = "vouchers/filter",
  GENERIC = "generic",
  GENERIC_EVENT = "generic/event",
}
