name: CI

on:
  push:
    branches:
    - master
    - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12.x'
    - run: npm install yarn
    - run: yarn install
    - run: yarn build
